# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core', '~> 5.9.0'
pod 'Firebase/Auth', '~> 5.9.0'

target 'MusiClover' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


  target 'MusiCloverTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MusiClover-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MusiClover-tvOS

  target 'MusiClover-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
